# -*- coding: utf-8 -*-
"""Untitled17.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjVoks0bs-9cRPk2yqcem5ALQT2SCf4s
"""

import os


# Telegram
BOT_TOKEN = os.getenv(
    "RELEASE_GUARD_BOT_TOKEN"
)

CHAT_ID = os.getenv(
    "RELEASE_GUARD_CHAT_ID"
)