# -*- coding: utf-8 -*-
"""Untitled17.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjVoks0bs-9cRPk2yqcem5ALQT2SCf4s
"""

from config import (
    BOT_TOKEN,
    CHAT_ID
)

from release_detector import (
    get_current_versions
)

from state_manager import (
    compare_version,
    save_state
)

from telegram_sender import (
    send_release_message
)



def main():


    current = get_current_versions()


    result = compare_version(
        current
    )


    if result["new_release"]:


        telegram_result = send_release_message(

            BOT_TOKEN,

            CHAT_ID,

            result["previous"],

            current

        )


        if telegram_result["ok"]:


            save_state(

                current["android_version"],

                current["ios_version"]

            )


            print(
                "Release detected and saved"
            )


        else:

            print(
                "Telegram failed"
            )


    else:


        print(
            "No new release"
        )



if __name__ == "__main__":

    main()