# -*- coding: utf-8 -*-
"""Untitled17.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjVoks0bs-9cRPk2yqcem5ALQT2SCf4s
"""

from google_play_scraper import app
import requests


def get_android_version():

    result = app(
        "com.sktelecom.tauth",
        lang="ko",
        country="kr"
    )

    return result["version"]



def get_ios_version():

    url = (
        "https://itunes.apple.com/"
        "lookup?id=1141258007"
    )

    response = requests.get(url)

    data = response.json()

    return data["results"][0]["version"]



def get_current_versions():

    return {

        "android_version": get_android_version(),

        "ios_version": get_ios_version()

    }