# -*- coding: utf-8 -*-
"""Untitled17.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjVoks0bs-9cRPk2yqcem5ALQT2SCf4s
"""

import json
import os
from datetime import datetime


STATE_FILE = "release_state.json"



def load_state():

    if not os.path.exists(STATE_FILE):

        return {

            "android_version": None,

            "ios_version": None

        }


    with open(
        STATE_FILE,
        "r",
        encoding="utf-8"
    ) as f:

        return json.load(f)



def save_state(android_version, ios_version):

    data = {

        "android_version": android_version,

        "ios_version": ios_version,

        "last_check":
            datetime.now()
            .strftime("%Y-%m-%d %H:%M:%S")

    }


    with open(
        STATE_FILE,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            data,
            f,
            ensure_ascii=False,
            indent=4
        )



def compare_version(current):

    previous = load_state()


    is_new_release = (

        previous["android_version"]
        != current["android_version"]

        or

        previous["ios_version"]
        != current["ios_version"]

    )


    return {

        "new_release": is_new_release,

        "previous": previous,

        "current": current

    }