# -*- coding: utf-8 -*-
"""Untitled17.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjVoks0bs-9cRPk2yqcem5ALQT2SCf4s
"""

import requests


def send_release_message(
        bot_token,
        chat_id,
        previous,
        current
):


    message = f"""
🚀 PASS Release Guard

PASS 신규 버전 배포가 감지되었습니다.

Android
{previous['android_version']}
➡️ {current['android_version']}


iOS
{previous['ios_version']}
➡️ {current['ios_version']}

지금부터
Release Monitoring 시작합니다.

Monitoring Time : 4시간
Check Interval : 10분
"""


    url = (
        f"https://api.telegram.org/"
        f"bot{bot_token}/sendMessage"
    )


    payload = {

        "chat_id": chat_id,

        "text": message

    }


    response = requests.post(
        url,
        data=payload
    )


    return response.json()