name: PASS Release Guard

on:
  workflow_dispatch:

  schedule:
    - cron: '*/10 * * * *'
jobs:
  release-check:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'


    - name: Install dependencies
      run: |
        pip install -r requirements.txt


    - name: Run Release Guard
      env:
        RELEASE_GUARD_BOT_TOKEN: ${{ secrets.RELEASE_GUARD_BOT_TOKEN }}
        RELEASE_GUARD_CHAT_ID: ${{ secrets.RELEASE_GUARD_CHAT_ID }}

      run: |
        python main.py
